[app]
domain = "localhost:8989"
port = 8989

[matrix]
homeserver = "localhost:8080"
server_name = "localhost:8480"
db = "postgres://postgres:postgres@host.docker.internal:5432/synapse?sslmode=disable"

[security]
allowed_origins = ["http://localhost:5173", "http://localcommune.com"]

[log]
max_size = 100
max_backups = 7
max_age = 30
compress = true

[capabilities.public_rooms]
list_rooms = true
view_hierarchy = true
read_messages = true

[cache]
public_rooms = true
